# Generated by Django 3.2.7 on 2021-10-02 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_published_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='published_at',
        ),
    ]
